=== captech/captech-common-components/commons-basic-os/src/main/resources/xml/OsInformation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="osInformation" type="osInformationType"/>
    <xs:complexType name="osInformationType">
        <xs:sequence>
            <xs:element type="dfInfoType" name="dfInfo" maxOccurs="1" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>Some text</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="cpuInfoType" name="cpuInfo" maxOccurs="1" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>Some text</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:sequence>
                <xs:element type="memoryInfoType" name="memoryInfo" maxOccurs="1" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Some text</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dfInfoType">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:int" name="status">
                <xs:annotation>
                    <xs:documentation>
                        Has following values:
                        0 = No error found
                        50 = Partial file system error
                        99 = System error
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" type="fileSystemsType" name="fileSystems">
                <xs:annotation>
                    <xs:documentation>Some text</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="coreInfosType">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" type="coreInfoType" name="coreInfo"/>
            <xs:element minOccurs="0" maxOccurs="1" type="timeType" name="time"/>
            <xs:element type="xs:string" name="systemError" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cpuInfoType">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:int" name="status">
                <xs:annotation>
                    <xs:documentation>
                        Has following values:
                        0 = No error found
                        50 = Partial cpu info system error
                        99 = System error
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="coreInfosType" name="coreInfos"/>
            <!--<xs:choice>-->
            <!--<xs:element minOccurs="1" maxOccurs="1" type="coreInfoType" name="coreInfo"/>-->
            <!--<xs:element minOccurs="1" maxOccurs="1" type="coreInfoErrorType" name="coreErrorInfo"/>-->
            <!--</xs:choice>-->
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="memoryInfoType">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:int" name="status">
                <xs:annotation>
                    <xs:documentation>
                        Has following values:
                        0 = No error found
                        50 = Partial cpu info system error
                        99 = System error
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" type="memoriesType" name="memories"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fileSystemsType">
        <xs:choice>
            <xs:element type="fileSystemType" name="fileSystem" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="xs:string" name="systemError" maxOccurs="1" minOccurs="1"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="infoType">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="dirName"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="devName"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:long" name="used"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:long" name="available"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:long" name="total"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:long" name="percentage"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fileSystemType">
        <xs:sequence>
            <xs:element type="infoType" name="info" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="error" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="coreInfoType">
        <xs:sequence>
            <xs:element type="xs:string" name="vendor"/>
            <xs:element type="xs:string" name="model"/>
            <xs:element type="xs:string" name="mhz"/>
            <xs:element type="xs:string" name="totalCpus"/>
            <xs:element type="coreType" name="core" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="coreInfoErrorType">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" type="xs:string" name="vendor"/>
            <xs:element maxOccurs="1" minOccurs="0" type="xs:string" name="model"/>
            <xs:element maxOccurs="1" minOccurs="0" type="xs:string" name="mhz"/>
            <xs:element maxOccurs="1" minOccurs="0" type="xs:string" name="totalCpus"/>
            <xs:element type="xs:string" name="systemError" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="coreType">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:int" name="id"/>
            <xs:element minOccurs="1" maxOccurs="1" type="timeType" name="time"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="timeType">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:float" name="user"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:float" name="sys"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:float" name="idle"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:float" name="combined"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="memoryType">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:int" name="ram"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="type"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:int" name="used"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:int" name="total"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:int" name="free"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="memoriesType">
        <xs:choice>
            <xs:element type="memoryType" name="memory" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="xs:string" name="systemError" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== captech/captech-common-components/commons-basic-os/src/main/resources/xml/OsInformation.xml
<?xml version="1.0" encoding="UTF-8"?>

<osInformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='OsInformation.xsd'>
    <!--DF based Information-->
    <dfInfo>
        <status>50</status>
        <fileSystems>
            <fileSystem>
                <info>
                    <!--Size information is represented in MB-->
                    <dirName>D:\</dirName>
                    <devName>D:\</devName>
                    <used>4718</used>
                    <available>0</available>
                    <total>4718</total>
                    <percentage>100</percentage>
                </info>
            </fileSystem>
            <fileSystem>
                <info>
                    <dirName>F:\</dirName>
                    <devName>\\oslo\users\eme</devName>
                </info>
                <error>Unable to fetch File System Usage information for F:\ {devName=\\oslo\users\eme, dirName=F:\}
                    Probable reason: Access is denied.
                </error>
            </fileSystem>
            <fileSystem>
                <info>
                    <!--Size information is represented in MB-->
                    <dirName>C:\</dirName>
                    <devName>C:\</devName>
                    <used>140704</used>
                    <available>9910</available>
                    <total>150614</total>
                    <percentage>94</percentage>
                </info>
            </fileSystem>
        </fileSystems>
    </dfInfo>
    <!--Cpu based Information-->
    <cpuInfo>
        <status>0</status>
        <coreInfos>
            <coreInfo>
                <vendor>Intel</vendor>
                <model>Core(TM) i7-2620M CPU @ 2.70GHz</model>
                <mhz>2693</mhz>
                <totalCpus>4</totalCpus>
                <core>
                    <id>0</id>
                    <time>
                        <!--Core time usage information is represented in % of the total amount of process time-->
                        <user>3.2</user>
                        <sys>3.2</sys>
                        <idle>93.6</idle>
                        <combined>6.4</combined>
                    </time>
                </core>
            </coreInfo>
            <coreInfo>
                <vendor>Intel</vendor>
                <model>Core(TM) i7-2620M CPU @ 2.70GHz</model>
                <mhz>2693</mhz>
                <totalCpus>4</totalCpus>
                <core>
                    <id>1</id>
                    <time>
                        <!--Core time usage information is represented in % of the total amount of process time-->
                        <user>3.01</user>
                        <sys>0</sys>
                        <idle>96.99</idle>
                        <combined>3.01</combined>
                    </time>
                </core>
            </coreInfo>
            <coreInfo>
                <vendor>Intel</vendor>
                <model>Core(TM) i7-2620M CPU @ 2.70GHz</model>
                <mhz>2693</mhz>
                <totalCpus>4</totalCpus>
                <core>
                    <id>2</id>
                    <time>
                        <!--Core time usage information is represented in % of the total amount of process time-->
                        <user>0</user>
                        <sys>3.01</sys>
                        <idle>96.99</idle>
                        <combined>3.01</combined>
                    </time>
                </core>
            </coreInfo>
            <coreInfo>
                <vendor>Intel</vendor>
                <model>Core(TM) i7-2620M CPU @ 2.70GHz</model>
                <mhz>2693</mhz>
                <totalCpus>4</totalCpus>
                <core>
                    <id>3</id>
                    <time>
                        <!--Core time usage information is represented in % of the total amount of process time-->
                        <user>6.4</user>
                        <sys>0</sys>
                        <idle>93.6</idle>
                        <combined>6.4</combined>
                    </time>
                </core>
            </coreInfo>
            <time>
                <!--Core time usage information is represented in % of the total amount of process time-->
                <user>8.49</user>
                <sys>2.33</sys>
                <idle>88.38</idle>
                <combined>10.83</combined>
            </time>
        </coreInfos>
    </cpuInfo>
    <!--Memory based Information-->
    <memoryInfo>
        <status>0</status>
        <memories>
            <memory>
                <!--In MB-->
                <ram>8104</ram>
                <type>mem</type>
                <used>4647</used>
                <total>8102</total>
                <free>3454</free>
            </memory>
            <memory>
                <!--In MB-->
                <type>swap</type>
                <used>5020</used>
                <total>16202</total>
                <free>11182</free>
            </memory>
        </memories>
    </memoryInfo>
</osInformation>
