=== captech/captech-common-components/commons-basic/src/test/resources/xml/pathMappings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="mappings" type="mappingsType"/>
    <xsd:complexType name="mappingsType">
        <xsd:sequence>
            <xsd:element type="mappingType" name="mapping" maxOccurs="unbounded" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="inputType">
        <xsd:sequence>
            <xsd:element name="path" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value=".+"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element type="serverType" name="server" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="outputType">
        <xsd:sequence>
            <xsd:element name="path" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value=".+"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element type="serverType" name="server" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="mappingType">
        <xsd:sequence>
            <xsd:element name="serviceType">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value=".{5,20}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="id">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value=".{1,20}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element type="outputType" name="output" minOccurs="0"/>
            <xsd:element type="inputType" name="input" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="serverType">
        <xsd:annotation>
            <xsd:documentation>Server Information</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="protocol" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="sftp"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="host" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value=".+"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="port" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="\d+"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="user" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value=".+"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:choice>
                <xsd:element name="password" minOccurs="1" maxOccurs="1">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value=".+"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="key" minOccurs="1" maxOccurs="1">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value=".+"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== captech/captech-common-components/commons-basic/src/test/resources/xml/pathMappings.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--<mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='pathMappings.xsd'>-->
<mappings>
    <!--Output Paths er paths on remote server-->
    <!--/bbs/datafangst/pp4/data/to_host/eFaktura-->

    <!--TROMS Fylkestrafikk-->

    <mapping>
        <serviceType>TRFNS</serviceType>
        <id>202</id>
        <output>
            <path>/bbs/datafangst/pp4/data/to_host/eFaktura</path>
        </output>
    </mapping>
    <mapping>
        <serviceType>TRFNS</serviceType>
        <id>203</id>
        <output>
            <path>/tTROTRA/Avvist</path>
        </output>
    </mapping>
    <mapping>
        <serviceType>TRFNM</serviceType>
        <id>201</id>
        <input>
            <path>/cifs/datafangst/eScanning/netscan-eScanning</path>
        </input>
    </mapping>
    <mapping>
        <serviceType>TRFNM</serviceType>
        <id>202</id>
        <output>
            <path>/bbs/datafangst/pp4/data/to_host/eFaktura</path>
        </output>
    </mapping>
    <mapping>
        <serviceType>TRFNM</serviceType>
        <id>203</id>
        <output>
            <path>/tTROTRA/Avvist</path>
        </output>
    </mapping>
</mappings>
